version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://imf_gadgetapi_user:oabbY6cQeDDcH1Yn18VEChwFv3TltZVj@db:5432/imf_gadgetapi
      - REDIS_HOST=redis
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    networks:
      - imf-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: imf_gadgetapi_user
      POSTGRES_PASSWORD: oabbY6cQeDDcH1Yn18VEChwFv3TltZVj
      POSTGRES_DB: imf_gadgetapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - imf-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - imf-network

volumes:
  postgres-data:
  redis-data:

networks:
  imf-network:
    driver: bridge
